--Display all games released after 1990.
SELECT * FROM VINTAGEGAMING WHERE RELEASEYEAR>1990

--Show all SNK games.
SELECT * FROM VINTAGEGAMING WHERE COMPANY='SNK'

--List games whose price is greater than 45.
SELECT * FROM VINTAGEGAMING WHERE PRICE>45

--Display all Arcade games.
SELECT * FROM VINTAGEGAMING WHERE CONSOLE='ARCADE'

--Show games whose rating is at least 9.5.
SELECT * FROM VINTAGEGAMING WHERE RATING>=9.5

--Display Platform games released before 1990.
SELECT * FROM VINTAGEGAMING WHERE RELEASEYEAR<1990

--Find games priced between 30 and 50.
SELECT * FROM VINTAGEGAMING WHERE PRICE BETWEEN 30 AND 50

--Display games whose names start with "Metal".
SELECT * FROM VINTAGEGAMING WHERE GAMENAME LIKE 'METAL%'

--Find the total copies sold.
SELECT SUM(COPIESSOLD) AS TOTAL_COPIES FROM VINTAGEGAMING 

--Find the average rating.
SELECT AVG(RATING) AS AVG_RATING FROM VINTAGEGAMING

--Find the maximum price.
SELECT MAX(PRICE) AS MAX_PRICE FROM VINTAGEGAMING

--Find the minimum release year.
SELECT MIN(RELEASEYEAR) AS MIN_RELEASEYEAR FROM VINTAGEGAMING

--Count total games.
SELECT COUNT(GAMENAME) AS TOTAL_GAMES FROM VINTAGEGAMING

--Find the average price.
SELECT AVG(PRICE) AS AVG_PRICE FROM VINTAGEGAMING

--Find the highest copies sold.
SELECT MAX(COPIESSOLD) AS HIGHEST_COPIESSOLD FROM VINTAGEGAMING

--Count games by company.
SELECT COMPANY,COUNT(*) AS FREQ FROM VINTAGEGAMING GROUP BY COMPANY

--Find average rating for each console.
SELECT CONSOLE,AVG(RATING) AS AVG_RAT FROM VINTAGEGAMING GROUP BY CONSOLE

--Find total copies sold by company.
SELECT COMPANY,SUM(COPIESSOLD) AS COPIES_SOLD FROM VINTAGEGAMING GROUP BY COMPANY

--Find maximum price for each genre.
SELECT GENRE,MAX(PRICE) AS MAX_PRICE FROM VINTAGEGAMING GROUP BY GENRE

--Count games in each console.
SELECT CONSOLE,COUNT(*) AS FREQ FROM VINTAGEGAMING GROUP BY CONSOLE

--Find average price for each genre.
SELECT GENRE,AVG(PRICE) AS AVG_PRICE FROM VINTAGEGAMING GROUP BY GENRE

--Display companies having more than 2 games.
SELECT COMPANY,COUNT(*) AS FREQ FROM VINTAGEGAMING GROUP BY COMPANY HAVING COUNT(*)>2

--Show consoles whose average rating is above 9.5.
SELECT CONSOLE,AVG(RATING) AS AVG_RAT FROM VINTAGEGAMING GROUP BY CONSOLE HAVING AVG(RATING)>9.5

--Display genres having more than 2 games.
SELECT GENRE,COUNT(*) AS FREQ FROM VINTAGEGAMING GROUP BY GENRE HAVING COUNT(*)>2

--Show companies whose total copies sold exceed 20 million.
SELECT COMPANY,SUM(COPIESSOLD) AS TOT_COP FROM VINTAGEGAMING GROUP BY COMPANY HAVING SUM(COPIESSOLD)>20

--Show consoles where maximum price is greater than 50.
SELECT CONSOLE,MAX(PRICE) AS MAX_PRICE FROM VINTAGEGAMING GROUP BY CONSOLE HAVING MAX(PRICE)>50

--Display genres whose average price is above 40.
SELECT GENRE,AVG(PRICE) AS AVG_PRICE FROM VINTAGEGAMING GROUP BY GENRE HAVING AVG(PRICE)>40

--Find the game(s) with the highest rating.
SELECT * FROM VINTAGEGAMING WHERE RATING=(SELECT MAX(RATING) FROM VINTAGEGAMING)

--Find the game(s) with the lowest price.
SELECT * FROM VINTAGEGAMING WHERE PRICE=(SELECT MIN(PRICE) FROM VINTAGEGAMING)

--Display games priced above the average price.
SELECT * FROM VINTAGEGAMING WHERE PRICE>(SELECT AVG(PRICE) FROM VINTAGEGAMING)

--Show games released before the average release year.
SELECT * FROM VINTAGEGAMING WHERE RELEASEYEAR<(SELECT AVG(RELEASEYEAR) FROM VINTAGEGAMING)

--Find games with copies sold greater than the average copies sold.
SELECT * FROM VINTAGEGAMING WHERE COPIESSOLD>(SELECT AVG(COPIESSOLD) FROM VINTAGEGAMING)

--Find the second highest price.
SELECT MAX(PRICE) AS SEC_HIGHEST FROM VINTAGEGAMING WHERE PRICE<(SELECT MAX(PRICE) FROM VINTAGEGAMING)

--Display games belonging to the same company as "Contra".
SELECT * FROM VINTAGEGAMING WHERE COMPANY=(SELECT COMPANY FROM VINTAGEGAMING WHERE GAMENAME='CONTRA')

--Find games released in the earliest year.
SELECT * FROM VINTAGEGAMING WHERE RELEASEYEAR=(SELECT MIN(RELEASEYEAR) FROM VINTAGEGAMING)

--Show games with ratings equal to the maximum rating.
SELECT * FROM VINTAGEGAMING WHERE RATING=(SELECT MAX(RATING) FROM VINTAGEGAMING)

--Display games priced less than the average price.
SELECT * FROM VINTAGEGAMING WHERE PRICE<(SELECT AVG(PRICE) FROM VINTAGEGAMING)

--Find companies that have games costing more than the average price.
SELECT DISTINCT COMPANY FROM VINTAGEGAMING WHERE PRICE>(SELECT AVG(PRICE) FROM VINTAGEGAMING)

--Show all games released after the release year of "Pac-Man".
SELECT * FROM VINTAGEGAMING WHERE RELEASEYEAR>(SELECT RELEASEYEAR FROM VINTAGEGAMING WHERE GAMENAME='PAC-MAN')

--Find games whose copies sold are greater than all SNK games' average copies sold.
SELECT * FROM VINTAGEGAMING WHERE COPIESSOLD>(SELECT AVG(COPIESSOLD) FROM VINTAGEGAMING WHERE Company='SNK')

